from jiwer import process_words

def write_error_markup_to_file(reference, candidate, out_file_path):
    """
    Checks candidate error types (insertion, deletion, substitution) comparing it to the reference

    Args:
        reference (str): transcript of the original text
        candidate (str): automatic transcript generated by a model
        out_file_path (str): file path where marked file will be placed
    """
    # compare reference and candidate
    result = process_words(reference, candidate)

    # identify operations of candidate words in comparison to reference
    alignment = result.alignments[0]
    
    ref_words = reference.split()
    hyp_words = candidate.split()
    
    ref_i = 0
    hyp_i = 0

    # to store words with html marking with color defined by error type
    html_output = []

    # mark mistakes by hanging their color in html
    for op in alignment:
        # if words are equel just add them to text
        if op.type == "equal":
            for _ in range(op.ref_end_idx - op.ref_start_idx):
                html_output.append(ref_words[ref_i])
                ref_i += 1
                hyp_i += 1
                
        # if a word was deleted from reference paint it red
        elif op.type == "delete":
            for _ in range(op.ref_end_idx - op.ref_start_idx):
                html_output.append(
                    f'<span style="color:red">{ref_words[ref_i]}</span>'
                )
                ref_i += 1
                
        # if it is extra word paint it blue
        elif op.type == "insert":
            for _ in range(op.hyp_end_idx - op.hyp_start_idx):
                html_output.append(
                    f'<span style="color:blue">{hyp_words[hyp_i]}</span>'
                )
                hyp_i += 1
        #if a word was subsituted show the origninal word and paint it orange
        elif op.type == "substitute":
            for _ in range(op.ref_end_idx - op.ref_start_idx):
                # [reference word -> candidate word]
                html_output.append(
                    f'<span style="color:orange">[{ref_words[ref_i]} -> {hyp_words[hyp_i]}]</span>'
                )
                ref_i += 1
                hyp_i += 1
    
    marked_text = " ".join(html_output)

    # full html page with marked candidate text
    html_page = f"""
    <html>
    <head>
    <title>ASR kļūdas</title>
    </head>
    <body style="font-family: Arial; line-height:1.6">
    
    <h2>Ar WER noteikto kļūdu vizualizācija</h2>
    
    <h3>Krāsu nozīme:</h3>
    <ul>
    <li><span style="color:red">Sarkans</span> = deletion (pazudūšais vārds)</li>
    <li><span style="color:blue">Zils</span> = insertion (lieks vārds)</li>
    <li><span style="color:orange">Oranžs</span> = substitution (pareizais vārds -> nepareizs vārds)</li>
    </ul>
    
    <p>{marked_text}</p>
    
    </body>
    </html>
    """
    
    with open(out_file_path, "w", encoding="utf-8") as f:
        f.write(html_page)